apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: details-fault
  namespace: default
spec:
  destination:
    name: details
  precedence: 2
  route:
  - labels:
      version: v1
  httpFault:
    abort:
      percent: 50
      httpStatus: 503
