apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: fortio-retries
spec:
  destination:
    name: fortio
  precedence: 1
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3  
